Repository DataIntellectTech/TorQ-Finance-Starter-Pack, pull requests merged in 2020-05, with the labels that each got.

#45 Code for the Engine process in the DQE
  appconfig/dqcconfig.csv
  appconfig/dqedetail.csv
  appconfig/dqengineconfig.csv
  appconfig/passwords/accesslist.txt
  appconfig/passwords/dqc.txt
  appconfig/process.csv
  docs/gettingstarted.md
  dqe/dqcdb/database/2020.04.17/configtable/.d
  dqe/dqcdb/database/2020.04.17/configtable/action
  dqe/dqcdb/database/2020.04.17/configtable/checkid
  dqe/dqcdb/database/2020.04.17/configtable/endtime
  dqe/dqcdb/database/2020.04.17/configtable/mode
  dqe/dqcdb/database/2020.04.17/configtable/params
  dqe/dqcdb/database/2020.04.17/configtable/params#
  dqe/dqcdb/database/2020.04.17/configtable/period
  dqe/dqcdb/database/2020.04.17/configtable/proc
  dqe/dqcdb/database/2020.04.17/configtable/proc#
  dqe/dqcdb/database/2020.04.17/configtable/starttime
  dqe/dqcdb/database/2020.04.17/results/.d
  dqe/dqcdb/database/2020.04.17/results/chkruntype
  dqe/dqcdb/database/2020.04.17/results/chkstatus
  dqe/dqcdb/database/2020.04.17/results/descp
  dqe/dqcdb/database/2020.04.17/results/descp#
  dqe/dqcdb/database/2020.04.17/results/endtime
  dqe/dqcdb/database/2020.04.17/results/funct
  dqe/dqcdb/database/2020.04.17/results/id
  dqe/dqcdb/database/2020.04.17/results/params
  dqe/dqcdb/database/2020.04.17/results/procs
  dqe/dqcdb/database/2020.04.17/results/procschk
  dqe/dqcdb/database/2020.04.17/results/result
  dqe/dqcdb/database/2020.04.17/results/starttime
  dqe/dqcdb/database/sym
  dqe/dqedb/database/2020.04.17/resultstab/.d
  dqe/dqedb/database/2020.04.17/resultstab/column
  dqe/dqedb/database/2020.04.17/resultstab/funct
  dqe/dqedb/database/2020.04.17/resultstab/procs
  dqe/dqedb/database/2020.04.17/resultstab/resvalue
  dqe/dqedb/database/2020.04.17/resultstab/table
  dqe/dqedb/database/sym
  dqedb/database/2020.01.06/.dqe.configtable/.d
  dqedb/database/2020.01.06/.dqe.configtable/host
  dqedb/database/2020.01.06/.dqe.configtable/id
  dqedb/database/2020.01.06/.dqe.configtable/loglevel
  dqedb/database/2020.01.06/.dqe.configtable/message
  dqedb/database/2020.01.06/.dqe.configtable/proctype
  dqedb/database/2020.01.06/.dqe.configtable/sym
  dqedb/database/2020.01.06/.dqe.configtable/time
  dqedb/database/2020.01.06/.dqe.results/.d
  dqedb/database/2020.01.06/.dqe.results/host
  dqedb/database/2020.01.06/.dqe.results/id
  dqedb/database/2020.01.06/.dqe.results/loglevel
  dqedb/database/2020.01.06/.dqe.results/message
  dqedb/database/2020.01.06/.dqe.results/proctype
  dqedb/database/2020.01.06/.dqe.results/sym
  dqedb/database/2020.01.06/.dqe.results/time
  dqedb/database/sym
  setenv.sh
Labels: enhancement

#40 Add dqe to FSP
  appconfig/dqcconfig.csv
  appconfig/dqedetail.csv
  appconfig/dqengineconfig.csv
  appconfig/passwords/accesslist.txt
  appconfig/passwords/dqc.txt
  appconfig/passwords/dqe.txt
  appconfig/process.csv
  docs/gettingstarted.md
  dqe/dqcdb/database/2020.04.17/configtable/.d
  dqe/dqcdb/database/2020.04.17/configtable/action
  dqe/dqcdb/database/2020.04.17/configtable/checkid
  dqe/dqcdb/database/2020.04.17/configtable/endtime
  dqe/dqcdb/database/2020.04.17/configtable/mode
  dqe/dqcdb/database/2020.04.17/configtable/params
  dqe/dqcdb/database/2020.04.17/configtable/params#
  dqe/dqcdb/database/2020.04.17/configtable/period
  dqe/dqcdb/database/2020.04.17/configtable/proc
  dqe/dqcdb/database/2020.04.17/configtable/proc#
  dqe/dqcdb/database/2020.04.17/configtable/starttime
  dqe/dqcdb/database/2020.04.17/results/.d
  dqe/dqcdb/database/2020.04.17/results/chkruntype
  dqe/dqcdb/database/2020.04.17/results/chkstatus
  dqe/dqcdb/database/2020.04.17/results/descp
  dqe/dqcdb/database/2020.04.17/results/descp#
  dqe/dqcdb/database/2020.04.17/results/endtime
  dqe/dqcdb/database/2020.04.17/results/funct
  dqe/dqcdb/database/2020.04.17/results/id
  dqe/dqcdb/database/2020.04.17/results/params
  dqe/dqcdb/database/2020.04.17/results/procs
  dqe/dqcdb/database/2020.04.17/results/procschk
  dqe/dqcdb/database/2020.04.17/results/result
  dqe/dqcdb/database/2020.04.17/results/starttime
  dqe/dqcdb/database/sym
  dqe/dqedb/database/2020.04.17/resultstab/.d
  dqe/dqedb/database/2020.04.17/resultstab/column
  dqe/dqedb/database/2020.04.17/resultstab/funct
  dqe/dqedb/database/2020.04.17/resultstab/procs
  dqe/dqedb/database/2020.04.17/resultstab/resvalue
  dqe/dqedb/database/2020.04.17/resultstab/table
  dqe/dqedb/database/sym
  setenv.sh
Labels: newfeature

#51 Fix select statement in metrics.q to work with kdb 4
  code/processes/metrics.q
Labels: bug
